[KREV-12] add list tasks by date
KrevetkiDev/todo-bot pull request #7
Opened 2024-07-07 15:41 UTC by wxhami

2024-07-07 15:57 UTC, vmedvedevpro requested changes

2024-07-07 15:57 UTC, vmedvedevpro commented on src/Krevetki.ToDoBot.Application/Common/Helpers/DateParser.cs
> +        var stringItems = inputMessage.Split('?');
```csharp
if(!inputMessage.StartWith('?')) return false;

if(DateOnly.TryParse(inputMessage.Skip(1), out var date))
{
<...>
}
```

2024-07-07 15:57 UTC, vmedvedevpro commented on src/Krevetki.ToDoBot.Application/Common/Models/DateDto.cs
> +    public DateOnly Date { get; set; }
Зачем тебе класс с одним свойством?

2024-07-07 15:57 UTC, vmedvedevpro commented on src/Krevetki.ToDoBot.Application/Messages.cs
> +    public const string ListTasksByDateSignalSymbol = "?";
Эта переменная в том числе должна использоваться в парсере

2024-07-07 15:57 UTC, vmedvedevpro commented on src/Krevetki.ToDoBot.Bot/DependencyInjection.cs
> +                .AddSingleton<IPipe<PipeContext>, ListTaskByDatePipe>()
Перенеси выше, зачем это в колбек пайпах?

2024-07-07 15:57 UTC, vmedvedevpro commented on src/Krevetki.ToDoBot.Application/ToDoItems/Commands/ChangeToDoItemStatus/ChangeToDoItemStatusHandler.cs
> +                new Message() { Text = Messages.CountTask(todayTasksList.Count - 1) },
Почему -1 здесь?

2024-07-07 15:57 UTC, vmedvedevpro commented on src/Krevetki.ToDoBot.Application/ToDoItems/Queries/ListTasksByDate/ListTaskByDateHandler.cs
> +        var keyboard =
У тебя если дата в прошлом, то не должно быть клавиатуры у дела

2024-07-07 15:57 UTC, vmedvedevpro commented on src/Krevetki.ToDoBot.Application/ToDoItems/Queries/ListTasksByDate/ListTaskByDateHandler.cs
> +        if (tasksList.Count == 0)
Этот блок должен быть выше foreach, чтобы не запускать проход по листу

2024-07-07 15:57 UTC, vmedvedevpro commented on src/Krevetki.ToDoBot.Bot/Pipes/Command/ListTasksByDateQueryPipe.cs
> +        var toDoItemParser = new DateParser();
Чтобы инициализировать класс парсера каждый раз при использовании его нужно сделать статическим

2024-07-08 10:02 UTC, wxhami commented on src/Krevetki.ToDoBot.Application/Common/Helpers/DateParser.cs
> +        var stringItems = inputMessage.Split('?');
не работает

2024-07-08 10:56 UTC, vmedvedevpro approved these changes

2024-07-08 10:56 UTC, vmedvedevpro commented on src/Krevetki.ToDoBot.Application/ToDoItems/Queries/ListTasksByDate/ListTaskByDateHandler.cs
> +            await MessageService.SendMessageAsync(
ретерна не хватает

2024-07-08 10:59 UTC, merged